services:
  - type: web
    name: hotel-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    plan: free

  - type: web
    name: hotel-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && ./node_modules/.bin/serve -s build
    plan: free
